### ISSUE TITLE
[ERROR] App cannot start!

### ISSUE THREAD

**Issue by Soi9x** [suchmememanyskill/Legendary-GUI#3]
System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at LegendaryMapperV2.Model.InstalledGameList.GetGamesAsList()
   at LegendaryMapperV2.Service.LegendaryGameManager.GetGames()
   at LegendaryGUIv2.ViewModels.MainViewModel..ctor(LegendaryAuth auth, MainWindowViewModel window)
   at LegendaryGUIv2.ViewModels.MainWindowViewModel.SetMainViewModel()
   at LegendaryGUIv2.ViewModels.MainWindowViewModel.OnLogin(LegendaryAuth a)
   at LegendaryMapperV2.Service.LegendaryAuth.<>c__DisplayClass13_0.<AttemptLogin>b__0(LegendaryCommand x)
   at LegendaryMapperV2.Service.LegendaryCommand.<Callback>b__28_0(CommandCallback x)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at LegendaryMapperV2.Service.LegendaryCommand.Callback(Terminal t)
   at LegendaryMapperV2.Service.Terminal.TrackProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Soi9x** [comment]
fixed! delete folder .config > done!
